routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::group(['prefix' => 'paypal','as'=>'paypal.'], function(){
    Route::get('pay', 'PaypalController@add_to_wallet')->name('pay');
    Route::get('success','PaypalController@onProcessingCourseSuccess')->name('success');
    Route::get('success2','PaypalController@onProcessingCourseSuccess2')->name('success');
    Route::get('canceled','PaypalController@onProcessingCourseCanceled')->name('canceled');
});


Route::get('/', function () {
    return redirect()->route('show_login');
});

Route::get('admin/login','Admin\AdminController@login')->name('show_login');
Route::post('admin/login','Admin\AdminController@doLogin')->name('do_login');
Route::post('admin/logout','Admin\AdminController@logout')->name('do_logout');

Route::group(['prefix' => 'admin','namespace'=>'Admin', 'middleware' => 'admin'], function()
{
    Route::get('dashboard',
        function (){
            return view('admin.main');
        }
    );

    // users

    Route::resource('users', 'UsersController');
    Route::resource('contacts', 'ContactUsController');
    Route::resource('orders', 'OrdersController');

    Route::get('terms/{id}','IndexController@terms')->name('terms');
    Route::post('terms-updated','IndexController@updateSettings')->name('updateSettings');


    Route::get('change_status','OrdersController@changeStatus')->name('change_status');
    Route::get('sending_email','OrdersController@sendingEmail')->name('sending_email');

    // drivers



    // get all users
});
Auth::routes();
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/breadcrumb.blade.php
<!-- Page header -->
<div class="page-header page-header-default">
    <div class="page-header-content">
        <div class="page-title">
            <h4><a href="{{Session::get('_previous')['url']}}" ><i class="icon-arrow-right6 position-left"></i></a> <span class="text-semibold">لوحة تحكم صياغه </span> - @yield('title')</h4>
        </div>

        <div class="heading-elements">
            <div class="heading-btn-group">
                <a href="{{asset('admin/dashboard')}}" class="btn btn-link btn-float has-text"><i class="icon-bars-alt text-primary"></i><span>بعض الاحصائيات</span></a>
                <a href="{{asset('admin/dashboard')}}" class="btn btn-link btn-float has-text"><i class="icon-users text-primary"></i> <span>أعضاء الاداره</span></a>
            </div>
        </div>
    </div>

    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="{{asset('admin/dashboard')}}"><i class="icon-home2 position-left"></i> لوحة التحكم</a></li>
            <li class="active">@yield('title')</li>
        </ul>
    </div>
</div>
<!-- /page header -->

resources/views/admin/city_map.blade.php
<div id="dir" >
    <div id="map" class="border-bottom" style="height: 500px;width: 100%"></div>
</div>

@section('script')
    {!! Html::script('https://maps.googleapis.com/maps/api/js?key=AIzaSyCsT140mx0UuES7ZwcfY28HuTUrTnDhxww&libraries=places&language=ar') !!}
    <script >
        function initMap() {
            var map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: 24.7128688, lng: 46.8126935},
                zoom: 9
            });

            if ($('#bounders').val()=='') {

                var bounds = [
                    {lat: 24.943944934407117, lng: 46.23451969062501},
                    {lat: 24.51485745266444, lng: 46.23451969062501},
                    {lat: 24.51485745266444, lng: 47.26998111640626},
                    {lat: 24.943944934407117, lng: 47.26998111640626}
                ];
            }else{
                var  bounds=JSON.parse($('#bounders').val());
                map.setCenter({
                    lat:bounds[0].lat,
                    lng:bounds[0].lng
                });
                map.setZoom(11);

            }

            // Construct the polygon.
            var color;
            if($('#color').val()==''){
                color='#ff0020';
            }else{
                color=$('#color').val();
            }
      /*      var Rectangle = new google.maps.Rectangle({
                bounds: bounds,
                fillColor:color,
                editable: true,
                draggable: true,
            });
            $('#color').change(function () {
               Rectangle.setOptions({fillColor:$('#color').val()});
            });
            Rectangle.setMap(map);

            Rectangle.addListener('bounds_changed',function () {
                console.log(Rectangle.getBounds().toJSON());
                $('#bounders').val(JSON.stringify(Rectangle.getBounds().toJSON()));
            });*/
            var marker = new google.maps.Marker({
                position: {lat:bounds[0].lat,lng:bounds[0].lng},
                map: map,
                draggable: true,
            });
            google.maps.event.addListener(marker, 'dragend', function(e) {
                $('#marker').val(JSON.stringify(marker.getPosition()));
            });
            var polygon = new google.maps.Polygon({
                paths: bounds,
                strokeColor: color,
                strokeOpacity: 0.8,
                strokeWeight: 2,
                fillColor: color,
                fillOpacity: 0.35,
                editable: true,
                draggable: true,

            });
            $('#color').change(function () {
                polygon.setOptions({fillColor:$('#color').val(),strokeColor:$('#color').val()});
            });
            polygon.setMap(map);
            polygon.getPaths().forEach(function(path, index) {
                google.maps.event.addListener(path, 'insert_at', function(){
                    console.log('insert');
                    console.log(pathToJSON(polygon.getPath().getArray()));
                });

                google.maps.event.addListener(path, 'remove_at', function(){
                    console.log('remove');
                    console.log(pathToJSON(polygon.getPath().getArray()));
                });

                google.maps.event.addListener(path, 'set_at', function(){
                    console.log('modified');
                    console.log(pathToJSON(polygon.getPath().getArray()));
                });
            });
            google.maps.event.addListener(polygon, 'dragend', function(){
                console.log('drag polygon');
                console.log(pathToJSON(polygon.getPath().getArray()));
            });




            /*  polygon.addListener('bounds_changed',function () {
              path=[];
              polygon.getPath().getArray().forEach(function (i) {
                  path.push({lat:i.lat(),lng:i.lng()});
              });
              $('#bounders').val(JSON.stringify(path));
              console.log(JSON.stringify(path));
          });*/



        }
        function pathToJSON(points){
            var path=[];
        points.forEach(function (i) {
                path.push({lat:i.lat(),lng:i.lng()});
            });
        path=JSON.stringify(path);
        $('#bounders').val(path);
        return path;
        }

        google.maps.event.addDomListener(window, 'load', initMap);
    </script>
@endsection

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        لوحة تحكم صياغه
        |
        @yield('title')</title>
    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Cairo" rel="stylesheet">
    <link href="{{asset('admin/assets/css/icons/icomoon/styles.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/assets/css/bootstrap.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/assets/css/core.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/assets/css/components.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/assets/css/colors.css')}}" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->
@yield('header')
<!-- Core JS files -->

</head>

<body>

<!-- Main navbar -->
<div class="navbar navbar-inverse">
    <div class="navbar-header">
        {{--<a class="navbar-brand" href="/dashboard"><img src="/admin/assets/images/logo.png" alt=""></a>--}}
        <a class="navbar-brand" href="{{url('/admin/dashboard')}}">لوحة تحكم صياغه</a>

        <ul class="nav navbar-nav visible-xs-block">
            <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
            <li><a  data-toggle="collapse" class="sidebar-mobile-main-toggle" data-target=".sidebar-category"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>
    </div>

    <div class="navbar-collapse collapse" id="navbar-mobile">
        <ul class="nav navbar-nav">
            <li><a class="sidebar-control sidebar-main-toggle hidden-xs"><i class="icon-paragraph-justify3"></i></a>
            </li>

        </ul>

        {{--<p class="navbar-text"><span class="label bg-success">متصل اﻵن</span></p>--}}

        <ul class="nav navbar-nav navbar-right">

            {{--<li class="dropdown language-switch">--}}
            {{--<a class="dropdown-toggle" data-toggle="dropdown">--}}
            {{--<img src="{{asset('admin/assets/images/flags/sa.png')}}" class="position-left" alt="">--}}
            {{--عربي--}}
            {{--</a>--}}
            {{--</li>--}}


            <li class="dropdown dropdown-user">
                <a class="dropdown-toggle" data-toggle="dropdown">
                    <span>{{auth::user()->name}}</span>
                    <i class="caret"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="#" onclick="$('#logout').submit()"><i class="icon-switch2"></i> تسجيل خروج</a></li>
                    {!! Form::open(['route'=>'logout','id'=>'logout','class'=>'hide']) !!}
                    {!! Form::close() !!}
                </ul>
            </li>


        </ul>
    </div>
</div>
<!-- /main navbar -->


<!-- Page container -->
<div class="page-container">

    <!-- Page content -->
    <div class="page-content">
    @include('admin.nav')
    <!-- Main content -->
        <div class="content-wrapper">
        @include('admin.breadcrumb')
        <!-- Content area -->
            <div class="content">
                @if(Session::has('success'))
                    <div class="alert  alert-styled-left"
                         style="background-color:#ce8936;border-color: #dc9846;color: white">
                        <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span
                                    class="sr-only">اغلاق</span></button>
                        <span class="text-semibold"></span>عظيم !<a href="#"
                                                                    class="alert-link"> {{ Session::get('success') }} </a>
                        .
                    </div>
                @endif

                @if(Session::has('error'))

                    <div class="alert bg-warning alert-styled-left">
                        <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span
                                    class="sr-only">اغلاق</span></button>
                        <span class="text-semibold"></span>عفواً !<a href="#"
                                                                     class="alert-link"> {{ Session::get('error') }} </a>
                        .
                    </div>
            @endif

            @yield('content')

            <!-- Footer -->
                <div class="footer text-muted text-center">

                    &copy; 2018. <a href="http://panorama-q.com">تم التطوير والبرمجة</a> بواسطة <a href="#"
                                                                                                   target="_blank">شركة
                        الفكرة الرائعة للحلول البرمجية </a>
                </div>
                <!-- /footer -->

            </div>
            <!-- /content area -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->
</div>





<!--    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/loaders/pace.min.js')}}"></script>-->
    <script type="text/javascript" src="{{asset('admin/assets/js/core/libraries/jquery.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/core/libraries/bootstrap.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/loaders/blockui.min.js')}}"></script>
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
{{-- <link href="{{asset('admin/assets/icon-picker/css/fontawesome-iconpicker.min.css')}}" rel="stylesheet">--}}

    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/styling/switchery.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/styling/uniform.min.js')}}"></script>





    <script type="text/javascript"
            src="{{asset('admin/assets/js/plugins/forms/selects/bootstrap_multiselect.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/ui/moment/moment.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/pickers/daterangepicker.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/selects/select2.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/pagination/bootpag.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/pagination/bs_pagination.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/pagination/datepaginator.min.js')}}"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>


        <script>

</script>

    {{--  @include('sweet::alert')--}}
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/ui/nicescroll.min.js')}}"></script>
    <!-- moniem comment by order of morsy-->
    {{--<script type="text/javascript" src="{{asset('admin/assets/js/core/app.js')}}"></script>--}}
<!-- moniem comment by order of morsy-->
    <script type="text/javascript" src="{{asset('admin/assets/js/pages/components_pagination.js')}}"></script>
    {{--<script type="text/javascript" src="{{asset('admin/assets/js/pages/layout_fixed_custom.js')}}"></script>--}}
    @yield('script')





<!--    com-->

{{--<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>--}}
@include('sweet::alert')
<!-- /page container -->

@stack('scripts')
<script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/selects/select2.min.js')}}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>

<script>
    $(document).ready(function () {
        $('.kar-tab').on('click' , function(e){
            e.preventDefault();
            $('.displayBlock').removeClass('displayBlock');
            $(this).next('ul.hidden-ul').toggleClass('displayBlock')
        })
        $('select').addClass('selectNew');
        $('.selectNew').select2();
    })


</script>
</body>
</html>

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>تسجيل الدخول</title>

    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Cairo" rel="stylesheet">
    <link href="{{asset('admin/assets/css/icons/icomoon/styles.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/assets/css/bootstrap.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/assets/css/core.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/assets/css/components.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/assets/css/colors.css')}}" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->

    <!-- Core JS files -->
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/loaders/pace.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/core/libraries/jquery.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/core/libraries/bootstrap.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/loaders/blockui.min.js')}}"></script>
    <!-- /core JS files -->

    <!-- Theme JS files -->
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/styling/uniform.min.js')}}"></script>

    <script type="text/javascript" src="{{asset('admin/assets/js/core/app.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/pages/login.js')}}"></script>
    <!-- /theme JS files -->

</head>

<body class="login-container" style="background-image: linear-gradient(#1d58e2, #1d68a7);  ;margin-bottom: 30px;">

<!-- Page container -->
<div class="page-container">

    <!-- Page content -->
    <div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Content area -->
            <div class="content">

                @if(session()->has('status'))
                <div class="alert alert-danger">
                    <center>{{session()->get('status')}}</center>
                </div>
                @endif

                <!-- Advanced login -->
                <form method="POST" action="{{ route('do_login') }}">
                    {!! csrf_field() !!}
                    <div class="panel panel-body login-form">
                        <div class="text-center">
                            <div class="icon-object text-warning-400" style=" background-image: linear-gradient(#1d58e2, #1d68a7); border:1px solid rgb(191, 145, 59)">
                                <h2>صياغه</h2>
                            </div>
                            <h5 class="content-group-lg">تسجيل الدخول <small class="display-block">ادخل بياناتك</small></h5>
                        </div>

                        <div class="form-group has-feedback has-feedback-left">
                            <input id="email" oninvalid="this.setCustomValidity('من فضلك قم بادخال الايميل بشكل صحيح')" type="email" placeholder="اكتب الايميل" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required autofocus>
                            <div class="form-control-feedback">
                                <i class="icon-user text-muted"></i>
                            </div>
                            @if ($errors->has('email'))
                                <span class="invalid-feedback">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                            @endif
                        </div>

                        <div class="form-group has-feedback has-feedback-left">

                            <input id="password" type="password" placeholder="اكتب الباسورد" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                            @if ($errors->has('password'))
                                <span class="invalid-feedback">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                            @endif
                            <div class="form-control-feedback">
                                <i class="icon-lock2 text-muted"></i>
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn bg-blue btn-block" style="background-image: linear-gradient(#1d58e2, #1d68a7);border-color: rgb(191, 145, 59)">تسجيل دخول <i class="icon-circle-left2 position-right"></i></button>
                        </div>
                        <span class="help-block text-center no-margin">جميع الحقوق محفوظة  <a href="#">شركة الفكرة الرائعة</a></span>
                    </div>
                </form>
                <!-- /advanced login -->

            </div>
            <!-- /content area -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</div>
<!-- /page container -->

</body>
</html>

resources/views/admin/main.blade.php
@extends('admin.layout')
@section('header')
    @endsection
@section('title')
الصفحة الرئيسية والاحصائيات
@endsection

@section('content')


    <div class="row">
        <div class="col-sm-6 col-md-3">
            <div class="panel panel-body bg-grey-400 has-bg-image">
                <div class="media no-margin">
                    <div class="media-body">
                        <h3 class="no-margin"> </h3>
                        <span class="text-uppercase text-size-mini">عدد الطلبات الجديدة</span>
                        <br>
                        {{\App\Order::where('status','new')->count()}}
                    </div>

                    <div class="media-right media-middle">
                        <i class="icon-users  icon-3x opacity-75"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-6 col-md-3">
            <div class="panel panel-body bg-success has-bg-image">
                <div class="media no-margin">
                    <div class="media-body">
                        <h3 class="no-margin">  </h3>
                        <span class="text-uppercase text-size-mini">عدد عضويات العملاء</span>
                        <br>
                        {{\App\User::where('is_admin',0)->count()}}
                    </div>

                    <div class="media-right media-middle">
                        <i class="icon-users2  icon-3x opacity-75"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-6 col-md-3">
            <div class="panel panel-body bg-info has-bg-image">
                <div class="media no-margin">
                    <div class="media-body">
                        <h3 class="no-margin">  </h3>
                        <span class="text-uppercase text-size-mini">عدد الطلبات المنتهيه</span>
                        <br>
                        {{\App\Order::where('status','finished')->count()}}
                    </div>

                    <div class="media-right media-middle">
                        <i class="icon-user-tie  icon-3x opacity-75"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-6 col-md-3">
            <div class="panel panel-body bg-pink-400 has-bg-image">
                <div class="media no-margin">
                    <div class="media-body">
                        <h3 class="no-margin">  </h3>
                        <span class="text-uppercase text-size-mini">عدد الطلبات المدفوعه </span>
                        <br>
                        {{\App\Order::where('status','payed')->count()}}
                    </div>

                    <div class="media-right media-middle">
                        <i class="icon-location4  icon-3x opacity-75"></i>
                    </div>
                </div>
            </div>
        </div>



        <div class="col-sm-6 col-md-3">
            <div class="panel panel-body bg-teal-700 has-bg-image">
                <div class="media no-margin">
                    <div class="media-body">
                        <h3 class="no-margin">  </h3>
                        <span class="text-uppercase text-size-mini">عدد طلبات صياغه عقد </span>
                        <br>
                        {{\App\Order::where('order_type','contract')->count()}}
                    </div>
                    <div class="media-right media-middle">
                        <i class="icon-location3  icon-3x opacity-75"></i>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-sm-6 col-md-3">
            <div class="panel panel-body bg-blue-700 has-bg-image">
                <div class="media no-margin">
                    <div class="media-body">
                        <h3 class="no-margin"> </h3>
                        <span class="text-uppercase text-size-mini">عدد طلبات المراجعة والاستشارة</span>
                        <br>
                        {{\App\Order::where('order_type','consultation')->count()}}
                    </div>

                    <div class="media-right media-middle">
                        <i class="icon-location3  icon-3x opacity-75"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-6 col-md-3">
            <div class="panel panel-body bg-orange-400 has-bg-image">
                <div class="media no-margin">
                    <div class="media-body">
                        <h3 class="no-margin">   </h3>
                        <span class="text-uppercase text-size-mini">عدد الطلبات الخاصة </span>
                        <br>
                        {{\App\Order::where('order_type','special')->count()}}
                    </div>
                    <div class="media-right media-middle">
                        <i class="icon-bin2  icon-3x opacity-75"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-6 col-md-3">
            <div class="panel panel-body bg-grey has-bg-image">
                <div class="media no-margin">
                    <div class="media-body">
                        <h3 class="no-margin">  </h3>
                        <span class="text-uppercase text-size-mini">عدد الرسائل </span>
                        <br>
                        {{\App\Contact_Us::count()}}
                    </div>

                    <div class="media-right media-middle">
                        <i class="icon-envelop3  icon-3x opacity-75"></i>
                    </div>
                </div>
            </div>
         </div>
    </div>
@endsection
@section('script')
@endsection

resources/views/admin/nav.blade.php
<!-- Main sidebar -->
<div class="sidebar sidebar-main ">
    <div class="sidebar-content">

        <!-- User menu -->
        <div class="sidebar-user">
            <div class="category-content">
                <div class="media">
                    <a href="#" class="media-left">
                        <img src="" class="img-circle img-sm" alt="">
                    </a>

                    <div class="media-body">
                        <span class="media-heading text-semibold">{{Auth::user()->name}}</span>
                        <div class="text-size-mini text-muted">
                            <i class="icon-pin text-size-small"></i> مدير الموقع
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- /user menu -->

        <!-- Main navigation -->
        <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">


                <ul class="navigation navigation-main navigation-accordion">
                    <!-- Main -->
                    <li class="navigation-header"><span>الاعدادات الرئيسية</span> <i class="icon-menu" title="Main pages"></i></li>
                    <li class="active">
                        <a href="{{asset('admin/dashboard')}}"><i
                                    class="icon-home4"></i> <span>الصفحة الرئيسية</span></a>
                    </li>

                    <li>
                        <a
                                href="{{asset('admin/contacts')}}"><i
                                    class="icon-envelop"></i> <span>الرسائل  </span></a>
                    </li>


                    <li>
                        <a
                                href="{{route('terms',['id'=>1])}}"><i
                                    class="icon-envelop"></i> <span>الشروط والاحكام </span></a>
                    </li>


                    <li class="navigation-header"><span>المستخدمين  </span>
                        <i class="icon-menu" title="Main pages"></i></li>
                    <li>
                        <a href="#" class="kar-tab"><i class="icon-users2"></i>
                            <span>العملاء</span></a>
                            <ul class="hidden-ul">
                            <li class="{{(Request::is('dashboard/client') ? 'active' : '')}}">
                                <a href="{{route('users.index')}}"><i class="icon-list"></i> كل العملاء</a>
                            </li>

                            <li class="{{ (Request::is('dashboard/client/create') ? 'active' : '')}}"><a
                                        href="{{route('users.create')}}"><i class="icon-user-plus"></i> اضافة
                                    عميل جديد</a>
                            </li>

                        </ul>
                    </li>

                    <li class="">
                        <a
                                href="{{asset('admin/orders')}}"><i
                                    class="icon-download"></i> <span> جميع الطلبات  </span></a>
                    </li>

                    <li class="">
                        <a
                                href="{{route('orders.index')}}?order_type=contract"><i
                                    class="icon-download"></i> <span>طلبات صياغة عقد  </span></a>
                    </li>


                    <li class="">
                        <a
                                href="{{route('orders.index')}}?order_type=contract"><i
                                    class="icon-download"></i> <span>طلبات مراجعة واستشارة  </span></a>
                    </li>


                    <li class="">
                        <a
                                href="{{route('orders.index')}}?order_type=contract"><i
                                    class="icon-download"></i> <span>طلبات حاصة  </span></a>
                    </li>

                    {{--<li>--}}
                        {{--<a href="#" class="kar-tab"><i class=" icon-package"></i> <span>التقييمات </span></a>--}}
                        {{--<ul class="hidden-ul">--}}
                            {{--<li class="{{(Request::is('dashboard/rates/orders-rate') ? 'active' : '')}}"><a--}}
                                        {{--href="{{route('admin.OrdersRate')}}"><i class="icon-list"></i> تقييمات الطلبات</a>--}}
                            {{--</li>--}}

                        {{--</ul>--}}
                    {{--</li>--}}


             {{--</li>--}}
            </div>
        </div>
        <!-- /main navigation -->

    </div>
</div>
<!-- /main sidebar -->