routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::group(['prefix' => 'paypal','as'=>'paypal.'], function(){
    Route::get('pay', 'PaypalController@add_to_wallet')->name('pay');
    Route::get('success','PaypalController@onProcessingCourseSuccess')->name('success');
    Route::get('success2','PaypalController@onProcessingCourseSuccess2')->name('success');
    Route::get('canceled','PaypalController@onProcessingCourseCanceled')->name('canceled');
});


Route::get('/', function () {
    return redirect()->route('show_login');
});

Route::get('admin/login','Admin\AdminController@login')->name('show_login');
Route::post('admin/login','Admin\AdminController@doLogin')->name('do_login');
Route::post('admin/logout','Admin\AdminController@logout')->name('do_logout');

Route::group(['prefix' => 'admin','namespace'=>'Admin', 'middleware' => 'admin'], function()
{
    Route::get('dashboard',
        function (){
            return view('admin.main');
        }
    );

    // users

    Route::resource('users', 'UsersController');
    Route::resource('contacts', 'ContactUsController');
    Route::resource('orders', 'OrdersController');

    Route::get('terms/{id}','IndexController@terms')->name('terms');
    Route::post('terms-updated','IndexController@updateSettings')->name('updateSettings');


    Route::get('change_status','OrdersController@changeStatus')->name('change_status');
    Route::get('sending_email','OrdersController@sendingEmail')->name('sending_email');

    // drivers



    // get all users
});
Auth::routes();
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/ContactController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Contact_Us;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts =Contact_Us::orderBy('id', 'DESC')->take(10)->get();

        // dd($contacts) ;
        return view('admin.contact.index',compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */




    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $contact =Contact_Us::findOrFail($id);


        return view('admin.contact.show',compact('contact'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

     /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Contact=Contact_Us::find($id);
        if ($Contact){
            $Contact->delete();
            alert()->success('تم حذف الرساله بنجاح');
            return back();
        }
        alert()->error('الرسالة التى تحاول حذفها غير موجودة ');
        return back();
    }
}

app/Http/Controllers/Api/contactController.php
<?php

namespace App\Http\Controllers\Api;

use App\Contact;
use App\Http\Traits\ApiResponses;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;

class contactController extends Controller
{
    use ApiResponses;

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'message' => 'required|string',
        ];
        $validation = $this->apiValidation($request, $rules);
        if ($validation instanceof Response) return $validation;
                $request['user_id'] = auth()->id();
                Contact::create($request->all());
            return $this->apiResponse(__('messages.success_msg_sent'));
    }

}

resources/views/admin/contact/index.blade.php
@extends('admin.layout')
@section('title')
     الرسائل
@endsection

@section('header')

@endsection
@section('content')

    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">كل الرسائل</h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="reload"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
            عرض كل لرسائل  الفرعية والتحكم بهم وبكل العمليات الخاصة بهم مع امكانية البحث وتصدير تقارير وملفات وطباعتهم
        </div>

        <table class="table datatable-button-init-basic">
            <thead>
            <tr>
                <th> # </th>
                <th>الرقم
                </th>
                <th>الاسم</th>
                <th>الايميل</th>
                <th>الرسالة</th>
                <th>العمليات</th>
            </tr>
            </thead>
            <tbody>
            @foreach($contacts as $key=>$item)
                <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$item->id}}</td>
                    <td>{{$item->name}}</td>
                    <td>{{$item->email}}</td>
                    <td>{{str_limit($item->message,100)}}</td>

                    {!!Form::open( ['route' => ['contacts.destroy',$item->id] ,'id'=>'delete-form'.$item->id, 'method' => 'Delete']) !!}
                    {!!Form::close() !!}
                    <td>
                        <a href="{{route('contacts.show',$item->id)}}"  data-toggle="tooltip" data-original-title="مشاهده"> <i class="icon-eye4 text-inverse text-info" style="margin-left: 10px"></i> </a>

                        <a href="#" onclick="Delete({{$item->id}})" data-toggle="tooltip" data-original-title="حذف"> <i class="icon-trash text-inverse text-danger" style="margin-left: 10px"></i> </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->




    <script>
        function Delete(id) {
            var item_id=id;
            console.log(item_id);
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف هذا الرساله ؟",
                icon: "warning",
                buttons: ["الغاء", "موافق"],
                dangerMode: true,

            }).then(function(isConfirm){
                if(isConfirm){
                    document.getElementById('delete-form'+item_id).submit();
                }
                else{
                    swal("تم االإلفاء", "حذف المدينة تم الغاؤه",'info',{buttons:'موافق'});
                }
            });
        }
    </script>


@endsection
@section('script')
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/tables/datatables/datatables.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/tables/datatables/extensions/buttons.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/selects/select2.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/pages/datatables_extension_buttons_init.js')}}"></script>
@endsection

resources/views/admin/contact/show.blade.php
@extends('admin.layout')
@section('title')
     الرسائل
@endsection

@section('header')

@endsection
@section('content')

    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">   رسالة من :  {{$contact->name}} </h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="reload"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
           <div class="row" style="padding: 20px">
                <p>     <b>الاسم </b> :{{$contact->name}}  </p>
                <p>     <b>الايميل </b> :{{$contact->email}}  </p>
               <p>     <b>الرسالة </b> :{{$contact->message}}  </p>
            </div>
        </div>
    </div>
    <!-- /basic initialization -->

    <script>
        function Delete(id) {
            var item_id=id;
            console.log(item_id);
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف هذا الرساله ؟",
                icon: "warning",
                buttons: ["الغاء", "موافق"],
                dangerMode: true,

            }).then(function(isConfirm){
                if(isConfirm){
                    document.getElementById('delete-form'+item_id).submit();
                }
                else{
                    swal("تم االإلفاء", "حذف المدينة تم الغاؤه",'info',{buttons:'موافق'});
                }
            });
        }
    </script>


@endsection
@section('script')
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/tables/datatables/datatables.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/tables/datatables/extensions/buttons.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/selects/select2.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/pages/datatables_extension_buttons_init.js')}}"></script>
@endsection